// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzgyuhxiahcunyiocvem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6Z3l1aHhpYWhjdW55aW9jdmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTY5OTUsImV4cCI6MjA2ODI3Mjk5NX0.4ZoPz-Yb5FgZgu0cBmx9MoX8V2c7WXVdUZVLJU80O98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});